### ISSUE TITLE
Empty line between blocks

### ISSUE THREAD

**Issue by robsonsobral** [primer/stylelint-config-primer#65]
Hi!

May you consider adding empty lines between line blocks? The list of properties is [sooooooooooo] long.

I can update the config and submit a pull request, if you agree.

Thank you!

**Comment by simurai** [comment]
Do you mean [these properties](https://github.com/primer/stylelint-config-primer/blob/c2174ecdeb0484ed47fcece9bfcec8681b6387b9/property-order.js)? And by adding an empty line, is that to "group" properties? Something like this:

```
  'max-height',
  'box-sizing',

  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',

  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
```

So there is no empty line between `max-height` and `box-sizing` since they are not part of a group, but add an empty line for things like `padding` and `margin`?

**Comment by robsonsobral** [comment]
Jesus! I'm really, really sorry, @simurai ! I've been working so mush that I don't remember to have opened #61 ! I just find it on the issues list, but... I don't recall at all of it! I'm sorry!
